### PR TITLE
build machine binary instead of downloading

### PR DESCRIPTION
**Pull request by wlan0**
@cjellick @ibuildthecloud

### CODE REVIEW

**Comment by cjellick** [comment]
@wlan0 Can you do the cloning of machine inside of the build directory instead of the root of the project? And can you add build and dist to gitignore?

**Comment by ibuildthecloud** [comment]
How do you actually run this?  Is the `Dockerfile` just a decoy?

**Comment by ibuildthecloud** [comment]
@wlan0 I just addressed @cjellick comments in my PR to switch to dapper.

**Comment by wlan0** [comment]
Cool, thanks!

**Pull request merged**
